version: "3.1"

volumes:
  psql_data:
    driver: local

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  memcached:
    image: memcached
    restart: always
    ports:
      - "11211:11211"

  db:
    image: postgres
    restart: always
    volumes:
      - "psql_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  nats:
    image: nats:latest
    command: ["-js", "-m", "8222"]
    restart: always
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8093:8080"
    environment:
      ADMINER_PLUGINS: tables-filter tinymce

  builder-api:
    build: .
    restart: always
    command: api
    environment:
      - NETWORK=mainnet
      - BEACON_URIS
      - REDIS_URI=redis:6379
      - POSTGRES_DSN=postgresql://postgres:postgres@db/postgres?sslmode=disable
      - NATS_URI=nats://nats:4222
    depends_on:
      - db
      - redis
      - nats
    ports:
      - "8080:8080"
